weights: yolov5s.pt
sparsity_strategy: strage1
min_ratio: 0.0
max_ratio: 1.0
sr: 0.0001
max_iter: 1
remain_ratio: 0.5
cfg: models/yolov5s-pruning.yaml
data: data/rsod.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
prune: false
sparsity: true
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp58
